// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgm-Fu1PKnLw4OOszdUDoSBGJl8gfeLrw',
    appId: '1:416577135451:web:1e65decac708044b92f07e',
    messagingSenderId: '416577135451',
    projectId: 'ecommerce-app-b9a35',
    authDomain: 'ecommerce-app-b9a35.firebaseapp.com',
    storageBucket: 'ecommerce-app-b9a35.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb3cXKak_7a580UnVKO9IXImuYusVY2ns',
    appId: '1:416577135451:android:f88ef909ac81380492f07e',
    messagingSenderId: '416577135451',
    projectId: 'ecommerce-app-b9a35',
    storageBucket: 'ecommerce-app-b9a35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtKqIxrG0ON-ge6j5Q1UITCy3aN41h9Do',
    appId: '1:416577135451:ios:e154c92d43bfd25a92f07e',
    messagingSenderId: '416577135451',
    projectId: 'ecommerce-app-b9a35',
    storageBucket: 'ecommerce-app-b9a35.appspot.com',
    androidClientId: '416577135451-qe0p5mbkhjundk9vojvijgo07b9du259.apps.googleusercontent.com',
    iosClientId: '416577135451-4ivnnn72v389k6ve2acsuhj15c8t54l2.apps.googleusercontent.com',
    iosBundleId: 'com.example.econmeracApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtKqIxrG0ON-ge6j5Q1UITCy3aN41h9Do',
    appId: '1:416577135451:ios:e154c92d43bfd25a92f07e',
    messagingSenderId: '416577135451',
    projectId: 'ecommerce-app-b9a35',
    storageBucket: 'ecommerce-app-b9a35.appspot.com',
    androidClientId: '416577135451-qe0p5mbkhjundk9vojvijgo07b9du259.apps.googleusercontent.com',
    iosClientId: '416577135451-4ivnnn72v389k6ve2acsuhj15c8t54l2.apps.googleusercontent.com',
    iosBundleId: 'com.example.econmeracApp',
  );
}
